ilr_profiles_generate_data:
    path:  /ilr_profiles_generate_data/
    defaults: { _controller: ILRProfilesGenerateBundle:Generate:index}

ilr_profiles_generate_data_For_1:
    path:  /ilr_profiles_generate_data/{uid}
    defaults: { _controller: ILRProfilesGenerateBundle:Generate:index}

ilr_profiles_get_profile_data:
    path:  /ilr_profiles_get_profile_data/
    defaults: { _controller: ILRProfilesGenerateBundle:GetProfileData:index}

ilr_profiles_index:
    path: /
    defaults: { _controller: ILRProfilesGenerateBundle:Welcome:index }

