ilr_profiles_generate_data:
    path:  /ilr_profiles_generate_data/
    defaults: { _controller: ILRProfilesGenerateBundle:Generate:index}

ilr_profiles_generate_data_For_1:
    path:  /ilr_profiles_generate_data/{uid}
    defaults: { _controller: ILRProfilesGenerateBundle:Generate:index}

ilr_profiles_generate_data_just_retransform:
    path:  /ilr_profiles_generate_data_retransform/
    defaults: { _controller: ILRProfilesGenerateBundle:Generate:retransform}

ilr_profiles_generate_ldap:
    path:  /ilr_profiles_generate_ldap/
    defaults: { _controller: ILRProfilesGenerateBundle:Generate:generateLdap}

ilr_profiles_generate_legacy:
    path:  /ilr_profiles_generate_legacy/
    defaults: { _controller: ILRProfilesGenerateBundle:Generate:generateLegacy}

ilr_profiles_generate_raw_ai:
    path:  /ilr_profiles_generate_raw_ai/
    defaults: { _controller: ILRProfilesGenerateBundle:Generate:generateRawAi}

ilr_profiles_dump_constants:
    path:  /ilr_profiles_dump_constants/
    defaults: { _controller: ILRProfilesGenerateBundle:Generate:dumpConstants}

ilr_profiles_get_profile_data:
    path:  /ilr_profiles_get_profile_data/
    defaults: { _controller: ILRProfilesGenerateBundle:GetProfileData:index}

ilr_profiles_index:
    path: /
    defaults: { _controller: ILRProfilesGenerateBundle:Welcome:index }

