parameters:
#    ilr_profiles_generate.example.class: ILRProfiles\GenerateBundle\Example

services:
#    ilr_profiles_generate.example:
#        class: %ilr_profiles_generate.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
